[package]
name = "smart_tablet"
version = "0.1.0"
authors = ["ostrosco <ostrosco@fastmail.fm>"]
license = "MIT"
edition = "2018"
build = "build.rs"

[dependencies]
actix-web = "3"
actix-files = "0.5"
